"""
Export V3 web-ready assets for the interactive map.

Copies processed GeoJSON, suitability/uncertainty overlays, and metadata
to data/tiles_v3/ for serving with darcy_v3.html.

Output: data/tiles_v3/ directory with all V3 web map assets.
"""
import json
import shutil
from pathlib import Path

PROCESSED = Path("data/processed")
TILES_V3 = Path("data/tiles_v3")
TILES_V3.mkdir(parents=True, exist_ok=True)

# ============================================================
# Check suitability and uncertainty overlays
# ============================================================
overlay_path = TILES_V3 / "suitability_overlay_v3.png"
uncert_path = TILES_V3 / "uncertainty_overlay_v3.png"
bounds_path = TILES_V3 / "bounds_v3.json"

if overlay_path.exists() and bounds_path.exists():
    with open(bounds_path) as f:
        bd = json.load(f)
    print(f"V3 suitability overlay exists: {overlay_path}")
    print(f"  Bounds: {bd.get('bounds')}")
    print(f"  Model: {bd.get('architecture')}")
    print(f"  Stats: {bd.get('stats')}")
else:
    print("WARNING: V3 suitability overlay not found.")
    print("  Run: python scripts_v3/21_build_model_v3.py")
    # Create placeholder bounds
    bounds_json = {
        "bounds": [-96.64, 40.37, -90.14, 43.50],
        "width": 0, "height": 0,
        "placeholder": True,
        "model": "v3_rf_kriging",
    }
    with open(bounds_path, "w") as f:
        json.dump(bounds_json, f, indent=2)

if uncert_path.exists():
    print(f"V3 uncertainty overlay exists: {uncert_path}")
else:
    print("  No uncertainty overlay (will be generated by model script)")

# ============================================================
# Copy vector assets to tiles_v3 directory
# ============================================================
print("\nCopying V3 vector assets...")

assets = {
    # V3-scored wells (primary)
    "iowa_sourcewater_wells_v3.geojson": PROCESSED / "iowa_sourcewater_wells_v3.geojson",
    # Covariate layers (input visualization)
    "iowa_surficial.geojson": PROCESSED / "iowa_surficial_simplified.geojson",
    "iowa_dtb_scored_zones.geojson": PROCESSED / "iowa_dtb_scored_zones.geojson",
    "iowa_landform_regions.geojson": PROCESSED / "iowa_landform_regions.geojson",
    # Shared assets
    "iowa_boundary.geojson": PROCESSED / "iowa_boundary.geojson",
    "epa_constraints.geojson": PROCESSED / "epa_constraints.geojson",
    "aquifers_iowa.geojson": PROCESSED / "aquifers_iowa.geojson",
}

# Fall back to V2 wells if V3 scoring hasn't run yet
if not (PROCESSED / "iowa_sourcewater_wells_v3.geojson").exists():
    assets["iowa_sourcewater_wells_v3.geojson"] = PROCESSED / "iowa_sourcewater_wells.geojson"
    print("  NOTE: Using V2 wells (V3 scoring not yet run)")

for dest_name, src_path in assets.items():
    if src_path.exists():
        shutil.copy(src_path, TILES_V3 / dest_name)
        size_kb = src_path.stat().st_size / 1024
        print(f"  Copied {dest_name} ({size_kb:.0f} KB)")
    else:
        print(f"  SKIP {dest_name} (not found)")

print(f"\nAll V3 web assets in {TILES_V3}/")
print("Ready to serve: python -m http.server 8081")
print("Then open: darcy_v3.html")
